### GET
get {{hostname}}

### GET Hello
# @name getHello
get http://localhost:3000/hello

### Show Hello value
get {{hostname}}/show/{{getHello.response.body.$.hello}}

### 
get {{hostname}}/crm


### get all blogs
get {{hostname}}/blogs


### Save new blog
post {{hostname}}/blogs
content-type: application/json

{
  "title": "Title1",
  "author": "Author1",
  "body": "body 1"
}

### publish queue
post {{hostname}}/rabbit/publish
Content-Type: application/json

{
  "message": "Hello World"
}


### Consume
get {{hostname}}/rabbit/consume
